# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import modelqueue


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('status', models.BigIntegerField(db_index=True, default=modelqueue.Status.waiting)),
            ],
        ),
    ]
